Enhanced support for pop-up date attribute editing
Esri/data-collection-ios pull request #267
Opened 2020-11-25 22:20 UTC by esreli

This PR introduces enhanced support for pop-up date attribute editing.

1. Introduces new table cell, `PopupAttributeDatePickerCell`, for use by devices running iOS 14. This cell leverages the new iOS 14 `UIDatePicker`, placing the UI element within the attribute cell rather than displaying a date picker in the keyboard area.
1. Introduces support for _time_ as well as date (iOS 13 & 14)

See related issues:
- [[Support for iOS 14]](https://github.com/ArcGIS/open-source-apps/issues/468)
- [[Editing popup date fields to support date and time]](https://github.com/ArcGIS/open-source-apps/issues/472)

### Screenshots

| iOS 13 | iOS 14 - in-line | iOS 14 - expanded |
| --- | --- | --- |
| ![Simulator Screen Shot - iPhone 11 Pro Max - 2020-11-25 at 14 03 20](https://user-images.githubusercontent.com/33433113/100286941-99c5b380-2f28-11eb-902b-50152eda92c9.png) | ![Simulator Screen Shot - iPhone 11 Pro Max - 2020-11-25 at 14 16 24](https://user-images.githubusercontent.com/33433113/100287083-ddb8b880-2f28-11eb-8a35-74f1dcf8a7d1.png) | ![Simulator Screen Shot - iPhone 11 Pro Max - 2020-11-25 at 14 16 27](https://user-images.githubusercontent.com/33433113/100287101-e610f380-2f28-11eb-970a-0929d4c51228.png) |

| Dark Mode | Dynamic Text Size | 
| --- | --- | 
| ![Simulator Screen Shot - iPhone 11 Pro Max - 2020-11-25 at 14 00 50](https://user-images.githubusercontent.com/33433113/100287168-09d43980-2f29-11eb-964a-1902026a398b.png) | ![Simulator Screen Shot - iPhone 11 Pro Max - 2020-11-25 at 14 01 05](https://user-images.githubusercontent.com/33433113/100287194-122c7480-2f29-11eb-96fb-c9377f01ff3b.png) |

| iPad - in-line | iPad - expanded |
| --- | --- |
| ![Simulator Screen Shot - iPad Pro (9 7-inch) - 2020-11-25 at 14 02 33](https://user-images.githubusercontent.com/33433113/100287249-2c665280-2f29-11eb-8048-7863c78632b0.png) | ![Simulator Screen Shot - iPad Pro (9 7-inch) - 2020-11-25 at 14 02 37](https://user-images.githubusercontent.com/33433113/100287279-34be8d80-2f29-11eb-8e14-2b432cef5418.png) |

2020-11-30 22:11 UTC, mhdostal requested changes

2020-11-30 22:11 UTC, mhdostal commented on data-collection/data-collection/View Controllers/Rich Popup View Controllers/Rich Popup View Controller/RichPopupDetailsViewController/RichPopupDetailsViewController+UITableViewDataSource.swift
> +                        ) as! PopupAttributeDatePickerCell
The `as! PopupAttributeDatePickerCell` doesn't seem necessary.

2020-11-30 22:11 UTC, mhdostal commented on data-collection/data-collection/View Controllers/Rich Popup View Controllers/Rich Popup View Controller/RichPopupDetailsViewController/RichPopupDetailsViewController+UITableViewDataSource.swift
> +                        ) as! PopupAttributeDateCell
Same here, doesn't seem necessary.

2020-11-30 22:11 UTC, mhdostal commented on data-collection/data-collection/View Controllers/Rich Popup View Controllers/Rich Popup View Controller/RichPopupDetailsViewController/Table Cells/Attribute Cells/PopupAttributeDatePickerCell.swift
> +        if editing {
Can this whole block just be:

```
datePicker.isHidden = !editing
attributeValueLabel.isHidden = editing
```

2020-11-30 22:26 UTC, esreli commented on data-collection/data-collection/View Controllers/Rich Popup View Controllers/Rich Popup View Controller/RichPopupDetailsViewController/RichPopupDetailsViewController+UITableViewDataSource.swift
> +                        ) as! PopupAttributeDatePickerCell
If you look at line 88, `cell` must adhere to the `PopupAttributeCell` protocol. As such, if I don't explicitly cast this cell, the type falls back to `UITableViewCell`, which does not adhere to the required protocol. I have to leave this as-is.

2020-11-30 22:26 UTC, esreli commented on data-collection/data-collection/View Controllers/Rich Popup View Controllers/Rich Popup View Controller/RichPopupDetailsViewController/RichPopupDetailsViewController+UITableViewDataSource.swift
> +                        ) as! PopupAttributeDateCell
ditto - https://github.com/Esri/data-collection-ios/pull/267#discussion_r532943999

2020-11-30 22:32 UTC, esreli commented
Thank you @mhdostal. I've addressed your review, would you have another look?

2020-12-03 20:33 UTC, mhdostal approved these changes

2020-12-03 20:45 UTC, esreli commented
@mhdostal i've force pushed a rebase that resolves some merge conflicts. Merging.

2020-12-03 20:45 UTC, merged