License level clarification
Esri/data-collection-ios pull request #274
Opened 2021-02-17 17:38 UTC by mhdostal

Updates the documentation regarding Lite license level; offline editing and syncing require a Basic license.

2021-02-17 20:13 UTC, esreli requested changes

2021-02-17 20:13 UTC, esreli commented on README.md
> +A Lite license is free and enables all of the capabilities required by this app, with the exception of offline editing and syncing offline edits back to a feature service.  For offline editing and sy
```suggestion
A Lite license is free and enables all of the capabilities required by this app, with the exception of offline editing and synchronizing offline edits back to a feature service.  For offline editing and synchronizing, you need a Basic license. Visit the developer's website to learn more about [licensing your ArcGIS Runtime app](https://developers.arcgis.com/pricing/licensing/) and the different [ArcGIS Runtime license levels](https://developers.arcgis.com/ios/license-and-deployment/license/).
```

2021-02-18 21:37 UTC, mhdostal commented
@esreli - this is once again ready for your review.

2021-02-18 21:55 UTC, esreli commented on README.md
> +A Lite license is free and enables all of the capabilities required by this app, with the exception of offline editing and synchronizing offline edits back to a feature service.  For offline editing
Two more notes here but I think we are nearly done here.

First, it feels a bit odd to me to say "a Lite license is free and enables all of the capabilities..." only to turn around and say, "with the exception of...". Maybe we can swap the word "all" for "most"?

Second, one of the links in this doc gets redirected so it's probably best that we change the URL to be that of the redirected page.

```suggestion
A Lite license is free and enables most of the capabilities required by this app, with the exception of offline editing and synchronizing offline edits back to a feature service. For offline editing and synchronizing, you need a Basic license. Visit the developer's website to learn more about [licensing your ArcGIS Runtime app](https://developers.arcgis.com/documentation/mapping-apis-and-location-services/licensing/license-your-app/) and the different [ArcGIS Runtime license levels](https://developers.arcgis.com/ios/license-and-deployment/license/).
```

2021-02-19 00:02 UTC, esreli approved these changes
Thanks!

2021-02-19 15:06 UTC, merged